"""Texas regions, cities and military communities."""
COST = "Nothing. Independent agents are paid by the carriers when you enroll, so comparing plans and reviewing your coverage each year is free to you."
EXIT = ("For the 2026 plan year UnitedHealthcare and Humana withdrew Medicare Advantage plans from a number of rural Texas counties, and Humana has announced further reductions for 2027. "
        "A plan leaving your county gives you a Special Enrollment Period and, in most cases, a guaranteed-issue right to a Medigap policy without health questions.")

REGIONS = [
    dict(slug="houston-gulf-coast", name="Houston Metro &amp; Gulf Coast", short="Greater Houston", scene="houston",
         eyebrow="Medicare by region · Houston, Galveston &amp; the Golden Triangle",
         h1="Medicare help across Greater Houston and the Gulf Coast",
         sub="Harris, Fort Bend, Montgomery, Galveston, Brazoria and Jefferson counties &mdash; the deepest plan menu in Texas, the Texas Medical Center, and a network question that starts with which of five big systems you use.",
         counties="Harris, Fort Bend, Montgomery, Galveston, Brazoria, Liberty, Chambers, Waller, Jefferson, Orange, Hardin",
         cities=["houston", "the-woodlands", "beaumont"],
         systems=["Houston Methodist", "Memorial Hermann", "MD Anderson Cancer Center", "Baylor St. Luke&rsquo;s / CommonSpirit", "HCA Houston Healthcare", "Kelsey-Seybold Clinic", "UTMB Health (Galveston)"],
         note="<p><strong>Local plans to know:</strong> KelseyCare Advantage, built on the Kelsey-Seybold system, is sold only in the Houston area; Houston Methodist and Memorial Hermann each contract with different carriers. If your doctor sits inside one system, that decides the shortlist before premiums do.</p>",
         intro=["More than a million people on Medicare live in Greater Houston, and the plan menu shows it: dozens of Medicare Advantage plans in Harris County, every Medigap carrier licensed in Texas, and the full Part D lineup. The trade-off is that Houston&rsquo;s care is organized into large systems that contract separately, so a $0-premium plan that includes Memorial Hermann may exclude Methodist, and MD Anderson contracts with only some Advantage plans.",
                "Along the coast and into the Golden Triangle the menu thins. Galveston County leans on UTMB, Jefferson County on Baptist and Christus, and the 2026 carrier pullbacks reached some of the rural counties between them. We compare what is sold at your ZIP code, not what is sold in the Loop."],
         faqs=[("Which Medicare plans are available in Houston?", "Harris County typically has the widest choice in Texas: dozens of Medicare Advantage plans from Humana, UnitedHealthcare, Aetna, Cigna, Wellcare, Blue Cross Blue Shield of Texas, KelseyCare Advantage and others, every Medigap carrier in the state, and all standalone Part D plans. Availability is set by county and ZIP code and changes each plan year."),
               ("Does MD Anderson accept Medicare Advantage?", "MD Anderson accepts Original Medicare and therefore any Medigap policy. It contracts with some Medicare Advantage plans and not others, and the contracts change. If MD Anderson is your care or a possibility, we confirm the plan&rsquo;s status in writing before you enroll."),
               ("How much does your help cost?", COST)]),
    dict(slug="dallas-fort-worth", name="Dallas&ndash;Fort Worth Metroplex", short="DFW", scene="dallas",
         eyebrow="Medicare by region · Dallas, Fort Worth &amp; the northern suburbs",
         h1="Medicare help across the Dallas&ndash;Fort Worth Metroplex",
         sub="Dallas, Tarrant, Collin, Denton, Rockwall and Ellis counties &mdash; seven million people, a wide Advantage menu, and three or four big systems that each contract on their own terms.",
         counties="Dallas, Tarrant, Collin, Denton, Rockwall, Ellis, Kaufman, Johnson, Parker, Hunt",
         cities=["dallas", "fort-worth", "arlington", "plano"],
         systems=["UT Southwestern Medical Center", "Baylor Scott &amp; White Health", "Texas Health Resources", "Medical City Healthcare (HCA)", "Methodist Health System", "JPS Health Network", "Parkland Health"],
         note="<p><strong>Local plans to know:</strong> Baylor Scott &amp; White Health Plan sells its own Advantage plans built on its system; Texas Health and UT Southwestern contract with different carriers. Collin and Denton counties are among the fastest-growing Medicare markets in the country, and the lineups change every October.</p>",
         intro=["The Metroplex has the second-deepest Medicare menu in Texas and one of the most fragmented care maps. UT Southwestern, Baylor Scott &amp; White, Texas Health Resources, Methodist and Medical City each run their own hospitals and clinics and each signs its own Advantage contracts, so the first question is never the premium; it is which system your doctors belong to.",
                "The carrier pullbacks for 2026 barely touched the core metro counties, but they did reach the rural counties on its edges. If you are in Hunt, Kaufman or Parker County and got a non-renewal notice, the guaranteed-issue window that comes with it is time-limited."],
         faqs=[("Which Medicare plans are available in Dallas&ndash;Fort Worth?", "Dallas, Tarrant, Collin and Denton counties typically offer dozens of Medicare Advantage plans, every Medigap carrier in Texas, and the full Part D lineup. Availability is set by county and changes each plan year; we compare what is sold at your address."),
               ("Is UT Southwestern in my plan&rsquo;s network?", "UT Southwestern accepts Original Medicare, and therefore any Medigap policy. It contracts with some Medicare Advantage plans and not others, and the list changes yearly. We confirm before you enroll."),
               ("How much does your help cost?", COST)]),
    dict(slug="central-texas-hill-country", name="Austin, Central Texas &amp; the Hill Country", short="Central Texas", scene="capitol",
         eyebrow="Medicare by region · Austin, Waco, Temple &amp; the Hill Country",
         h1="Medicare help across Austin, Central Texas and the Hill Country",
         sub="Travis, Williamson, Hays, Bell, McLennan and the Hill Country counties &mdash; the state&rsquo;s fastest-growing retirement corridor, Sun City Texas, Fort Cavazos, and Baylor Scott &amp; White&rsquo;s home turf.",
         counties="Travis, Williamson, Hays, Bastrop, Caldwell, Bell, Coryell, McLennan, Burnet, Llano, Gillespie, Kerr, Blanco, Comal (north)",
         cities=["austin", "georgetown", "waco", "fort-cavazos"],
         systems=["Ascension Seton", "St. David&rsquo;s HealthCare", "Baylor Scott &amp; White (Temple, Round Rock, Waco)", "UT Health Austin", "Ascension Providence (Waco)", "Peterson Health (Kerrville)"],
         note="<p><strong>Local plans to know:</strong> Baylor Scott &amp; White Health Plan and its Temple-based system anchor Bell and McLennan counties; Ascension Seton and St. David&rsquo;s split Austin. Hill Country counties west of Austin have thinner Advantage menus and some of the longest drives to specialty care in the state.</p>",
         intro=["Central Texas is where Texans retire to: Georgetown&rsquo;s Sun City, the lake towns around Marble Falls, Kerrville and Fredericksburg. Austin and Round Rock have a deep Advantage menu split between Ascension Seton and St. David&rsquo;s; Temple and Waco are Baylor Scott &amp; White country; and the Hill Country proper has a short menu and long drives, which is where a Medigap policy&rsquo;s any-provider access earns its premium.",
                "The region also holds Fort Cavazos and its retiree community around Killeen and Harker Heights, where TRICARE For Life changes the calculation entirely."],
         faqs=[("Which Medicare plans are available in Austin?", "Travis and Williamson counties typically offer a wide Medicare Advantage menu, every Medigap carrier in Texas, and the full Part D lineup. Hill Country counties to the west have fewer Advantage plans. We compare what is sold at your address."),
               ("Does Sun City Texas in Georgetown have its own Medicare plans?", "No, but Williamson County&rsquo;s lineup is broad, and St. David&rsquo;s Georgetown, Baylor Scott &amp; White Round Rock and Ascension Seton Williamson each contract with different plans. Which system your doctors belong to decides the shortlist."),
               ("How much does your help cost?", COST)]),
    dict(slug="san-antonio-south-texas", name="San Antonio &amp; South Texas", short="San Antonio", scene="alamo",
         eyebrow="Medicare by region · San Antonio, New Braunfels, Laredo &amp; the brush country",
         h1="Medicare help across San Antonio and South Texas",
         sub="Bexar, Comal, Guadalupe, Webb and the brush-country counties &mdash; Military City USA, Joint Base San Antonio, and a care map split between University Health, Methodist, Baptist and Christus.",
         counties="Bexar, Comal, Guadalupe, Wilson, Atascosa, Medina, Kendall, Webb, Val Verde, Uvalde, Frio, Kinney, Maverick",
         cities=["san-antonio", "joint-base-san-antonio"],
         systems=["University Health", "Methodist Healthcare", "Baptist Health System", "Christus Santa Rosa", "Brooke Army Medical Center (military)", "Laredo Medical Center", "Uvalde Memorial"],
         note="<p><strong>Local plans to know:</strong> Bexar County has one of the highest Medicare Advantage enrollment rates of any large county in the country, and a large TRICARE For Life population that changes what &ldquo;best plan&rdquo; means. Webb County (Laredo) and the brush-country counties have thin menus and, for 2026, carrier withdrawals.</p>",
         intro=["San Antonio is one of the most Advantage-heavy Medicare markets in America, with University Health, Methodist, Baptist and Christus each contracting on their own terms and a large military-retiree population using TRICARE For Life on top of Medicare. The plan that fits a retired master sergeant in Universal City is rarely the plan that fits a retiree in Alamo Heights.",
                "South and west of the city, the menu thins fast. Laredo, Del Rio, Eagle Pass and Uvalde each rely on one or two hospitals, and rural South Texas was among the areas where carriers pulled plans for 2026."],
         faqs=[("Which Medicare plans are available in San Antonio?", "Bexar County typically offers a wide Medicare Advantage menu, every Medigap carrier in Texas, and the full Part D lineup. Webb County and the rural counties south and west have fewer Advantage plans. We compare what is sold at your address."),
               ("I have TRICARE For Life. Which plan should I look at?", "With TFL you already have a supplement-like layer and creditable drug coverage, so a Medigap policy and a Part D plan are usually unnecessary. An MA-only Advantage plan can add dental or vision without duplicating drug coverage. See our Joint Base San Antonio and Veterans pages."),
               ("How much does your help cost?", COST)]),
    dict(slug="rio-grande-valley", name="Rio Grande Valley", short="the Valley", scene="gulf",
         eyebrow="Medicare by region · McAllen, Harlingen, Brownsville &amp; South Padre",
         h1="Medicare help across the Rio Grande Valley",
         sub="Hidalgo, Cameron, Willacy and Starr counties &mdash; home to 100,000 Winter Texans each year, DHR Health, and some of the highest Medicare Advantage and dual-eligible enrollment in the nation.",
         counties="Hidalgo, Cameron, Willacy, Starr",
         cities=["mcallen"],
         systems=["DHR Health (Edinburg)", "South Texas Health System", "Rio Grande Regional (HCA)", "Valley Baptist (Harlingen, Brownsville)", "Harlingen Medical Center", "Starr County Memorial"],
         note="<p><strong>Local plans to know:</strong> The Valley has very high Medicare Advantage enrollment and a large population with both Medicare and Texas Medicaid, so Dual Special Needs Plans are a bigger part of the menu here than anywhere else in Texas. Winter Texans, by contrast, usually need coverage that works in two states.</p>",
         intro=["The Valley is two Medicare markets in one. Year-round residents choose from a deep Advantage menu built around DHR Health, South Texas Health System and Valley Baptist, and a large share qualify for both Medicare and Medicaid, which makes STAR+PLUS and D-SNPs central. Winter Texans from Minnesota, Iowa and Ontario arrive in November with plans from home that may cover only emergencies here.",
                "We work both sides: confirming a Valley plan&rsquo;s network for residents, and helping Winter Texans understand which of their plans travels and whether a Medigap policy or a supplement from home is the right tool."],
         faqs=[("Which Medicare plans are available in McAllen and the Valley?", "Hidalgo and Cameron counties typically offer a broad Medicare Advantage menu, including many Dual Special Needs Plans, plus every Medigap carrier in Texas and the full Part D lineup. Availability is set by county and changes each plan year."),
               ("I am a Winter Texan. Does my plan from home work here?", "A Medigap policy with Original Medicare works anywhere in the U.S. Most Medicare Advantage HMOs cover only emergencies outside their service area; some PPOs cover routine care out of network at higher cost. See our Winter Texans guide, and our sister site for Minnesota residents."),
               ("How much does your help cost?", COST)]),
    dict(slug="east-texas", name="East Texas &amp; the Piney Woods", short="East Texas", scene="pines",
         eyebrow="Medicare by region · Tyler, Longview, Lufkin, Nacogdoches &amp; Texarkana",
         h1="Medicare help across East Texas and the Piney Woods",
         sub="Smith, Gregg, Angelina, Nacogdoches, Bowie and the timber counties &mdash; strong regional hospitals in Tyler and Longview, thin menus in the counties between, and some of the 2026 carrier pullbacks.",
         counties="Smith, Gregg, Harrison, Angelina, Nacogdoches, Bowie, Cherokee, Henderson, Rusk, Panola, Shelby, Polk, Anderson",
         cities=["tyler"],
         systems=["UT Health East Texas (Tyler)", "Christus Trinity Mother Frances", "Christus Good Shepherd (Longview)", "Longview Regional", "Woodland Heights &amp; Christus St. Michael (Texarkana)", "Nacogdoches Medical Center"],
         note="<p><strong>What to watch:</strong> East Texas has more retirees per county than most of the state and fewer carriers per county. Several rural East Texas counties saw Advantage plans withdrawn for 2026; if yours did, the guaranteed-issue window to buy a Medigap policy is time-limited.</p>",
         intro=["East Texas is hospital-town country: Tyler and Longview anchor the region with UT Health East Texas, Christus and Longview Regional, and the counties around them lean on those systems for anything beyond primary care. Advantage menus are shorter here than in the metros and shrank in places for 2026, which is where Original Medicare with a Medigap policy earns its keep.",
                "Many East Texans also carry VA benefits through the Overton and Tyler clinics and the Shreveport VA across the line; how those coordinate with Medicare is on our Veterans page."],
         faqs=[("Which Medicare plans are available in Tyler and East Texas?", "Smith and Gregg counties typically offer a moderate Medicare Advantage menu, every Medigap carrier in Texas, and the full Part D lineup. Many rural East Texas counties have fewer Advantage plans, and some lost plans for 2026."),
               ("My Advantage plan is leaving my East Texas county. What now?", EXIT),
               ("How much does your help cost?", COST)]),
    dict(slug="west-texas-panhandle", name="West Texas, the Panhandle &amp; the Permian Basin", short="West Texas", scene="panhandle",
         eyebrow="Medicare by region · Lubbock, Amarillo, Midland&ndash;Odessa, Abilene &amp; San Angelo",
         h1="Medicare help across West Texas, the Panhandle and the Permian Basin",
         sub="Lubbock, Potter, Randall, Midland, Ector, Taylor and Tom Green counties, and the wide-open counties around them &mdash; strong regional hospitals, long drives, and the thinnest Advantage menus in the state.",
         counties="Lubbock, Potter, Randall, Midland, Ector, Taylor, Tom Green, Hale, Hockley, Howard, Scurry, Wichita, Deaf Smith, Gray, Hutchinson",
         cities=["lubbock", "amarillo", "midland"],
         systems=["Covenant Health (Lubbock)", "UMC Health System (Lubbock)", "BSA Health System (Amarillo)", "Northwest Texas Healthcare", "Midland Memorial", "Medical Center Health System (Odessa)", "Hendrick Health (Abilene)", "Shannon Medical Center (San Angelo)"],
         note="<p><strong>What to watch:</strong> The Panhandle and Permian counties outside the hub cities were among the hardest hit by the 2026 carrier withdrawals; some counties now have one or two Advantage plans or none. Original Medicare with a Medigap policy covers every hospital in the region without a network, and that is often the practical answer out here.</p>",
         intro=["West Texas Medicare is a distance problem. Lubbock, Amarillo, Midland&ndash;Odessa, Abilene and San Angelo each have solid regional systems, but the counties between them may be an hour or more from a hospital, and Advantage networks that look fine on paper can be a two-hour drive in practice. For 2026 several rural counties out here lost Advantage plans altogether.",
                "That is why so many West Texans keep Original Medicare with a Medigap policy: it works at Covenant, UMC, BSA and Midland Memorial alike, and at the Lubbock or Amarillo VA clinics for veterans who carry both."],
         faqs=[("Which Medicare plans are available in Lubbock or Amarillo?", "Lubbock, Potter and Randall counties typically offer a moderate Medicare Advantage menu, every Medigap carrier in Texas, and the full Part D lineup. Rural counties around them have fewer Advantage plans and some lost plans for 2026."),
               ("My plan pulled out of my West Texas county. What now?", EXIT),
               ("How much does your help cost?", COST)]),
    dict(slug="coastal-bend", name="Coastal Bend", short="the Coastal Bend", scene="gulf",
         eyebrow="Medicare by region · Corpus Christi, Rockport, Port Aransas &amp; Victoria",
         h1="Medicare help across the Coastal Bend",
         sub="Nueces, San Patricio, Aransas, Kleberg and Victoria counties &mdash; Corpus Christi&rsquo;s two hospital systems, NAS Corpus Christi retirees, and a Winter Texan season along the bays.",
         counties="Nueces, San Patricio, Aransas, Kleberg, Jim Wells, Bee, Refugio, Victoria, Calhoun",
         cities=["corpus-christi"],
         systems=["Christus Spohn Health System", "Corpus Christi Medical Center (HCA)", "Citizens Medical Center (Victoria)", "DeTar Healthcare (Victoria)"],
         note="<p><strong>What to watch:</strong> Corpus Christi&rsquo;s menu is moderate and its care is split between Christus Spohn and HCA&rsquo;s Corpus Christi Medical Center, which contract with different plans. Rockport, Port Aransas and Aransas Pass host Winter Texans whose plans from home may cover only emergencies here.</p>",
         intro=["The Coastal Bend is a smaller version of the Valley&rsquo;s two-market problem: year-round residents choosing between plans built around Christus Spohn or Corpus Christi Medical Center, and a seasonal population along the bays whose Minnesota or Michigan plans stop at the state line. NAS Corpus Christi and NAS Kingsville add a military-retiree layer with TRICARE For Life.",
                "Outside Nueces County the menu thins, and Victoria and the ranch counties inland lean on one hospital apiece."],
         faqs=[("Which Medicare plans are available in Corpus Christi?", "Nueces County typically offers a moderate Medicare Advantage menu, every Medigap carrier in Texas, and the full Part D lineup. Aransas, Refugio and the inland counties have fewer Advantage plans."),
               ("I winter in Rockport. Does my plan from home work here?", "A Medigap policy with Original Medicare works anywhere in the U.S. Most Medicare Advantage HMOs cover only emergencies outside their service area. See our Winter Texans guide."),
               ("How much does your help cost", COST)]),
]

def city(slug, name, county, region, scene, sub, intro, systems, communities, faqs, nearby):
    return dict(slug=slug, name=name, county=county, region=region, scene=scene, sub=sub, intro=intro, systems=systems, communities=communities, faqs=faqs, nearby=nearby)

CITIES = [
    city("houston", "Houston", "Harris County", "houston-gulf-coast", "houston",
         "From the Heights to Clear Lake, Houston has the deepest Medicare menu in Texas &mdash; and the most ways to pick a plan that leaves your doctor out. The comparison here starts with your hospital system.",
         ["Harris County offers dozens of Medicare Advantage plans, every Medigap carrier licensed in Texas and the full Part D lineup. The catch is that Houston&rsquo;s care is organized into large systems that contract separately: Houston Methodist, Memorial Hermann, Baylor St. Luke&rsquo;s, HCA and Kelsey-Seybold. KelseyCare Advantage covers Kelsey-Seybold and little else; other plans include Methodist but not Hermann, or the reverse.",
          "MD Anderson accepts Original Medicare and contracts with only some Advantage plans, which is why so many Houstonians with a cancer history keep a Medigap policy. We compare what is actually offered at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a supplement so you can see the trade-off plainly."],
         ["Houston Methodist", "Memorial Hermann", "MD Anderson Cancer Center", "Baylor St. Luke&rsquo;s Medical Center", "HCA Houston Healthcare", "Kelsey-Seybold Clinic"],
         "The Heights, Montrose, West University, Bellaire, Memorial, Kingwood, Clear Lake, Pearland, Sugar Land, Katy, Cypress, Pasadena, Baytown",
         [("Which Medicare plans are available in Houston?", "Harris County typically has the widest choice in Texas: dozens of Medicare Advantage plans, every Medigap carrier in the state, and all standalone Part D plans. Availability is set by ZIP code and changes each plan year; we compare what is offered at your address."),
          ("Will my Houston Methodist or Memorial Hermann doctors take a Medicare Advantage plan?", "It depends on the specific plan&rsquo;s network, and the contracts change every year. Before you enroll we confirm your providers at Methodist, Hermann, St. Luke&rsquo;s, HCA or Kelsey-Seybold are in-network and your prescriptions are on the formulary, so there are no surprises in January."),
          ("How much does your help cost?", COST)],
         ["the-woodlands", "beaumont", "corpus-christi"]),
    city("san-antonio", "San Antonio", "Bexar County", "san-antonio-south-texas", "alamo",
         "Military City USA has one of the highest Medicare Advantage enrollment rates in the country, a large TRICARE For Life population, and four hospital systems that each contract on their own terms.",
         ["Bexar County&rsquo;s Advantage menu is deep and its care is split among University Health, Methodist Healthcare, Baptist Health System and Christus Santa Rosa. A plan that includes Methodist may exclude University, and Brooke Army Medical Center at Fort Sam Houston serves military retirees under TRICARE rules that Medicare plans do not change.",
          "Because so many San Antonians carry TRICARE For Life, the &ldquo;best&rdquo; plan here is often an MA-only Advantage plan for dental and vision, or simply Original Medicare with TFL and nothing else. For everyone else we compare Advantage against a Medigap policy with your doctors, prescriptions and travel in front of us."],
         ["University Health", "Methodist Healthcare", "Baptist Health System", "Christus Santa Rosa", "Brooke Army Medical Center (TRICARE)", "Audie L. Murphy VA Hospital"],
         "Alamo Heights, Stone Oak, Universal City, Converse, Helotes, Leon Valley, Schertz, Boerne, New Braunfels, Seguin",
         [("Which Medicare plans are available in San Antonio?", "Bexar County typically offers a wide Medicare Advantage menu, every Medigap carrier in Texas, and the full Part D lineup. Availability is set by ZIP code and changes each plan year."),
          ("I have TRICARE For Life. Do I need a Medigap policy or Part D?", "Usually neither. TFL pays secondary to Medicare and its pharmacy is creditable drug coverage. An MA-only Advantage plan can add dental or vision without duplicating your drug benefit. See our Joint Base San Antonio page."),
          ("How much does your help cost?", COST)],
         ["joint-base-san-antonio", "austin", "corpus-christi"]),
    city("dallas", "Dallas", "Dallas County", "dallas-fort-worth", "dallas",
         "Dallas County has a deep plan menu and a fragmented care map: UT Southwestern, Baylor, Methodist, Medical City and Parkland each contract with different Advantage plans.",
         ["Dallas offers dozens of Medicare Advantage plans, every Medigap carrier in Texas and the full Part D lineup. The network question is the whole question: UT Southwestern, Baylor University Medical Center, Methodist Dallas, Medical City Dallas and Texas Health Presbyterian each sign their own Advantage contracts, and Baylor Scott &amp; White sells plans built on its own system.",
          "We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy so the trade-off is plain."],
         ["UT Southwestern Medical Center", "Baylor University Medical Center", "Methodist Dallas Medical Center", "Medical City Dallas", "Texas Health Presbyterian Dallas", "Parkland Health"],
         "Lakewood, Oak Cliff, Preston Hollow, Lake Highlands, Richardson, Garland, Mesquite, Irving, Carrollton, DeSoto, Duncanville",
         [("Which Medicare plans are available in Dallas?", "Dallas County typically offers dozens of Medicare Advantage plans, every Medigap carrier in Texas, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is UT Southwestern in my Advantage plan&rsquo;s network?", "UT Southwestern accepts Original Medicare and therefore any Medigap policy, and contracts with some Advantage plans and not others. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["fort-worth", "arlington", "plano"]),
    city("austin", "Austin", "Travis County", "central-texas-hill-country", "capitol",
         "Austin&rsquo;s Medicare menu is broad and split between two systems, Ascension Seton and St. David&rsquo;s, with Baylor Scott &amp; White and UT Health Austin growing fast.",
         ["Travis County offers a wide Advantage menu, every Medigap carrier in Texas and the full Part D lineup. Ascension Seton (including Dell Seton) and St. David&rsquo;s HealthCare contract with different carriers, so which one your doctors belong to shapes the shortlist; Baylor Scott &amp; White&rsquo;s Austin and Round Rock hospitals add a third.",
          "Austin retirees travel more than most, and many keep a lake place or a grandchild&rsquo;s spare room in another state, which is where a Medigap policy&rsquo;s any-provider access matters. We compare both paths with your doctors and your calendar."],
         ["Ascension Seton / Dell Seton", "St. David&rsquo;s HealthCare", "Baylor Scott &amp; White (Austin, Round Rock)", "UT Health Austin", "Austin VA Outpatient Clinic"],
         "Westlake, Tarrytown, Hyde Park, Circle C, Pflugerville, Cedar Park, Leander, Lakeway, Bee Cave, Dripping Springs, Kyle, Buda",
         [("Which Medicare plans are available in Austin?", "Travis County typically offers a wide Medicare Advantage menu, every Medigap carrier in Texas, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Are Seton and St. David&rsquo;s in the same plans?", "Rarely both in every plan. Each system contracts with some Advantage carriers and not others; with Original Medicare and a Medigap policy there is no network to check. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["georgetown", "san-antonio", "waco"]),
    city("fort-worth", "Fort Worth", "Tarrant County", "dallas-fort-worth", "ranch",
         "Fort Worth and Tarrant County have the Metroplex&rsquo;s wide plan menu with a care map of their own: Texas Health Harris, JPS, Baylor All Saints and Medical City Fort Worth.",
         ["Tarrant County offers dozens of Advantage plans, every Medigap carrier in Texas and the full Part D lineup. Texas Health Harris Methodist, JPS Health Network, Baylor Scott &amp; White All Saints and Medical City Fort Worth each contract separately, and Fort Worth&rsquo;s NAS JRB adds a military-retiree layer with TRICARE For Life.",
          "We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and lay Advantage beside a Medigap policy."],
         ["Texas Health Harris Methodist", "JPS Health Network", "Baylor Scott &amp; White All Saints", "Medical City Fort Worth", "Cook Children&rsquo;s (adult specialty referrals)", "Fort Worth VA Outpatient Clinic"],
         "TCU area, Westover Hills, Ridglea, Benbrook, Keller, North Richland Hills, Haltom City, Burleson, Weatherford, Azle",
         [("Which Medicare plans are available in Fort Worth?", "Tarrant County typically offers dozens of Medicare Advantage plans, every Medigap carrier in Texas, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is Texas Health Harris in my plan&rsquo;s network?", "Texas Health contracts with some Advantage plans and not others, changing year to year. With Original Medicare and a Medigap policy there is no network. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["arlington", "dallas", "plano"]),
    city("el-paso", "El Paso", "El Paso County", "west-texas-panhandle", "desert",
         "El Paso sits 550 miles from Austin and shares a care map with Fort Bliss, New Mexico and Juárez. Its Medicare menu is its own, and the network question includes William Beaumont.",
         ["El Paso County offers a moderate Advantage menu, every Medigap carrier in Texas and the full Part D lineup. University Medical Center of El Paso, The Hospitals of Providence and Las Palmas Del Sol contract with different carriers; Fort Bliss retirees use William Beaumont Army Medical Center under TRICARE rules; and many El Pasoans see doctors in Las Cruces, which an Advantage network may or may not include.",
          "The El Paso VA Health Care System is the largest veterans&rsquo; provider in the region; how it coordinates with Medicare is on our Fort Bliss and Veterans pages."],
         ["University Medical Center of El Paso", "The Hospitals of Providence", "Las Palmas Del Sol Healthcare", "William Beaumont Army Medical Center (TRICARE)", "El Paso VA Health Care System"],
         "Westside, Upper Valley, Kern Place, Eastside, Northeast, Horizon City, Socorro, Canutillo, Anthony, Las Cruces-area families",
         [("Which Medicare plans are available in El Paso?", "El Paso County typically offers a moderate Medicare Advantage menu, every Medigap carrier in Texas, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Can I see a doctor in Las Cruces with a Texas plan?", "With Original Medicare and a Medigap policy, yes. With a Medicare Advantage plan, only if the New Mexico provider is in that plan&rsquo;s network, which we confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["fort-bliss", "midland", "lubbock"]),
    city("arlington", "Arlington", "Tarrant County", "dallas-fort-worth", "dallas",
         "Arlington, Grand Prairie and Mansfield sit in the middle of the Metroplex with the full menu and two hospitals, Texas Health Arlington Memorial and Medical City Arlington, that contract differently.",
         ["Mid-cities residents have Tarrant County&rsquo;s deep Advantage menu, every Medigap carrier in Texas and the full Part D lineup, and can drive to Dallas or Fort Worth for specialty care. Which of those systems a plan includes is the first thing we check.",
          "We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["Texas Health Arlington Memorial", "Medical City Arlington", "Methodist Mansfield", "Baylor Scott &amp; White Grand Prairie"],
         "Arlington, Grand Prairie, Mansfield, Kennedale, Pantego, Dalworthington Gardens",
         [("Which Medicare plans are available in Arlington?", "Tarrant County typically offers dozens of Medicare Advantage plans, every Medigap carrier in Texas, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is Texas Health Arlington Memorial in my plan&rsquo;s network?", "It depends on the plan and the year. We confirm your hospital and doctors are in-network before you enroll."),
          ("How much does your help cost?", COST)],
         ["fort-worth", "dallas"]),
    city("corpus-christi", "Corpus Christi", "Nueces County", "coastal-bend", "gulf",
         "The Sparkling City has two hospital systems, a naval air station, and a Winter Texan season along the bays &mdash; three different Medicare questions in one county.",
         ["Nueces County offers a moderate Advantage menu, every Medigap carrier in Texas and the full Part D lineup. Christus Spohn and HCA&rsquo;s Corpus Christi Medical Center contract with different carriers, and NAS Corpus Christi and NAS Kingsville retirees carry TRICARE For Life, which changes the calculation.",
          "Rockport, Port Aransas and Aransas Pass fill with Winter Texans each fall whose plans from home may cover only emergencies here; our Winter Texans guide covers which plans travel."],
         ["Christus Spohn Shoreline &amp; South", "Corpus Christi Medical Center (HCA)", "Corpus Christi VA Outpatient Clinic", "NAS Corpus Christi (TRICARE)"],
         "Corpus Christi, Portland, Rockport, Port Aransas, Aransas Pass, Ingleside, Robstown, Kingsville",
         [("Which Medicare plans are available in Corpus Christi?", "Nueces County typically offers a moderate Medicare Advantage menu, every Medigap carrier in Texas, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is Christus Spohn in my plan&rsquo;s network?", "Christus Spohn and Corpus Christi Medical Center contract with different Advantage plans, changing year to year. With Original Medicare and a Medigap policy there is no network. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["mcallen", "san-antonio", "houston"]),
    city("plano", "Plano", "Collin County", "dallas-fort-worth", "dallas",
         "Plano, Frisco, McKinney and Allen are among the fastest-growing Medicare markets in the country, with Medical City Plano, Texas Health Plano and Baylor Scott &amp; White Plano all contracting on their own terms.",
         ["Collin County has the Metroplex&rsquo;s deep Advantage menu, every Medigap carrier in Texas and the full Part D lineup, and its lineups change every October as carriers chase its growth. Medical City Plano, Texas Health Presbyterian Plano, Baylor Scott &amp; White Plano and the UT Southwestern and Children&rsquo;s campuses in Frisco each sign their own contracts.",
          "We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["Medical City Plano", "Texas Health Presbyterian Plano", "Baylor Scott &amp; White Plano", "UT Southwestern Frisco", "Medical City McKinney"],
         "Plano, Frisco, McKinney, Allen, Richardson, Murphy, Wylie, Prosper, Celina",
         [("Which Medicare plans are available in Plano?", "Collin County typically offers dozens of Medicare Advantage plans, every Medigap carrier in Texas, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is Medical City Plano in my plan&rsquo;s network?", "It depends on the plan and the year. We confirm your hospital and doctors are in-network before you enroll."),
          ("How much does your help cost?", COST)],
         ["dallas", "arlington"]),
    city("lubbock", "Lubbock", "Lubbock County", "west-texas-panhandle", "panhandle",
         "The Hub City serves a 26-county region: Covenant and UMC are the two systems, and the counties around Lubbock were among those that lost Advantage plans for 2026.",
         ["Lubbock County offers a moderate Advantage menu, every Medigap carrier in Texas and the full Part D lineup. Covenant Health and UMC Health System (Texas Tech&rsquo;s teaching hospital) contract with different carriers, and because patients drive in from Plainview, Levelland and Brownfield, a plan&rsquo;s network has to reach the whole South Plains.",
          "Several South Plains counties lost Advantage plans for 2026. Original Medicare with a Medigap policy works at Covenant and UMC alike, which is why it is the practical answer for many families out here."],
         ["Covenant Health", "UMC Health System", "Lubbock Heart &amp; Surgical Hospital", "Lubbock VA Outpatient Clinic"],
         "Lubbock, Wolfforth, Shallowater, Slaton, Levelland, Plainview, Brownfield, Post",
         [("Which Medicare plans are available in Lubbock?", "Lubbock County typically offers a moderate Medicare Advantage menu, every Medigap carrier in Texas, and the full Part D lineup. Surrounding South Plains counties have fewer Advantage plans and some lost plans for 2026."),
          ("My plan pulled out of my county near Lubbock. What now?", EXIT),
          ("How much does your help cost?", COST)],
         ["amarillo", "midland", "el-paso"]),
    city("mcallen", "McAllen", "Hidalgo County", "rio-grande-valley", "gulf",
         "McAllen, Edinburg, Mission and Pharr have one of the most Advantage-heavy Medicare markets in America, DHR Health at its center, and a Winter Texan population that doubles some neighborhoods each January.",
         ["Hidalgo County offers a deep Advantage menu with many Dual Special Needs Plans, every Medigap carrier in Texas and the full Part D lineup. DHR Health, South Texas Health System and Rio Grande Regional contract separately, and a large share of residents qualify for both Medicare and Texas Medicaid, which makes STAR+PLUS and D-SNPs central to the comparison.",
          "Winter Texans are the other half of the market: retirees from Minnesota, Iowa, Michigan and Ontario whose plans from home may cover only emergencies here. We work both sides."],
         ["DHR Health (Edinburg)", "South Texas Health System", "Rio Grande Regional Hospital", "Mission Regional Medical Center", "McAllen VA Outpatient Clinic"],
         "McAllen, Edinburg, Mission, Pharr, Weslaco, Mercedes, Donna, Alamo, San Juan, Hidalgo",
         [("Which Medicare plans are available in McAllen?", "Hidalgo County typically offers a broad Medicare Advantage menu, including many Dual Special Needs Plans, every Medigap carrier in Texas, and the full Part D lineup, changing each plan year."),
          ("I am a Winter Texan in McAllen. Does my plan from home work here?", "A Medigap policy with Original Medicare works anywhere in the U.S. Most Advantage HMOs cover only emergencies outside their service area. See our Winter Texans guide."),
          ("How much does your help cost?", COST)],
         ["corpus-christi", "san-antonio"]),
    city("the-woodlands", "The Woodlands", "Montgomery County", "houston-gulf-coast", "pines",
         "The Woodlands, Conroe and Spring have Houston&rsquo;s big systems on their doorstep &mdash; Methodist, Memorial Hermann, St. Luke&rsquo;s and MD Anderson all have campuses here &mdash; and Montgomery County&rsquo;s own plan lineup.",
         ["Montgomery County offers a deep Advantage menu, every Medigap carrier in Texas and the full Part D lineup. Houston Methodist The Woodlands, Memorial Hermann The Woodlands, St. Luke&rsquo;s The Woodlands and MD Anderson The Woodlands each contract separately, and HCA&rsquo;s Conroe hospital adds a fifth.",
          "The Woodlands is also one of Texas&rsquo;s largest retirement destinations, and many residents split the year elsewhere; our Winter Texans guide covers which plans travel."],
         ["Houston Methodist The Woodlands", "Memorial Hermann The Woodlands", "St. Luke&rsquo;s Health&ndash;The Woodlands", "MD Anderson The Woodlands", "HCA Houston Healthcare Conroe"],
         "The Woodlands, Conroe, Spring, Shenandoah, Oak Ridge North, Magnolia, Montgomery, Willis",
         [("Which Medicare plans are available in The Woodlands?", "Montgomery County typically offers a deep Medicare Advantage menu, every Medigap carrier in Texas, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is MD Anderson The Woodlands in my Advantage plan?", "MD Anderson contracts with some Advantage plans and not others, changing year to year, and accepts Original Medicare and any Medigap policy. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["houston", "beaumont"]),
    city("tyler", "Tyler", "Smith County", "east-texas", "pines",
         "Tyler is East Texas&rsquo;s medical hub, with UT Health East Texas and Christus Trinity Mother Frances serving a dozen counties &mdash; several of which lost Advantage plans for 2026.",
         ["Smith County offers a moderate Advantage menu, every Medigap carrier in Texas and the full Part D lineup. UT Health East Texas and Christus Trinity Mother Frances contract with different carriers, and because patients drive in from Jacksonville, Athens, Palestine and Mineola, a plan&rsquo;s network needs to reach the whole region.",
          "Several rural East Texas counties lost Advantage plans for 2026; a non-renewal notice opens a time-limited guaranteed-issue window for a Medigap policy."],
         ["UT Health East Texas", "Christus Trinity Mother Frances", "Christus Mother Frances&ndash;Tyler", "Tyler VA Clinic"],
         "Tyler, Whitehouse, Lindale, Bullard, Jacksonville, Athens, Mineola, Palestine, Longview-area families",
         [("Which Medicare plans are available in Tyler?", "Smith County typically offers a moderate Medicare Advantage menu, every Medigap carrier in Texas, and the full Part D lineup. Surrounding counties have fewer Advantage plans and some lost plans for 2026."),
          ("My plan is leaving my East Texas county. What now?", EXIT),
          ("How much does your help cost?", COST)],
         ["dallas", "houston"]),
    city("waco", "Waco", "McLennan County", "central-texas-hill-country", "capitol",
         "Waco and McLennan County are Baylor Scott &amp; White and Ascension Providence country, with a moderate plan menu and Fort Cavazos retirees an hour south.",
         ["McLennan County offers a moderate Advantage menu, every Medigap carrier in Texas and the full Part D lineup. Baylor Scott &amp; White Hillcrest and Ascension Providence contract with different carriers, and Baylor Scott &amp; White Health Plan sells plans built on its own system.",
          "We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["Baylor Scott &amp; White Hillcrest", "Ascension Providence", "Waco VA Medical Center (Doris Miller)"],
         "Waco, Woodway, Hewitt, Robinson, Bellmead, McGregor, West, Marlin",
         [("Which Medicare plans are available in Waco?", "McLennan County typically offers a moderate Medicare Advantage menu, every Medigap carrier in Texas, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is Hillcrest in my plan&rsquo;s network?", "Baylor Scott &amp; White Hillcrest and Ascension Providence contract with different Advantage plans. With Original Medicare and a Medigap policy there is no network. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["fort-cavazos", "austin", "dallas"]),
    city("amarillo", "Amarillo", "Potter County", "west-texas-panhandle", "panhandle",
         "Amarillo serves the whole Panhandle, and the Panhandle&rsquo;s rural counties were among the hardest hit by the 2026 Advantage withdrawals. BSA and Northwest Texas are the two systems.",
         ["Potter and Randall counties offer a moderate Advantage menu, every Medigap carrier in Texas and the full Part D lineup. BSA Health System and Northwest Texas Healthcare contract with different carriers, and because patients drive in from Dumas, Pampa, Hereford and Borger, a plan&rsquo;s network has to reach the whole top of Texas.",
          "Many Panhandle counties now have one or two Advantage plans or none. Original Medicare with a Medigap policy works at BSA and Northwest alike, and at the Amarillo VA for veterans who carry both."],
         ["BSA Health System", "Northwest Texas Healthcare System", "Amarillo VA Health Care System"],
         "Amarillo, Canyon, Dumas, Pampa, Borger, Hereford, Dalhart, Perryton",
         [("Which Medicare plans are available in Amarillo?", "Potter and Randall counties typically offer a moderate Medicare Advantage menu, every Medigap carrier in Texas, and the full Part D lineup. Rural Panhandle counties have fewer Advantage plans and some lost plans for 2026."),
          ("My plan pulled out of my Panhandle county. What now?", EXIT),
          ("How much does your help cost?", COST)],
         ["lubbock", "midland"]),
    city("georgetown", "Georgetown", "Williamson County", "central-texas-hill-country", "hillcountry",
         "Georgetown, home to Sun City Texas, is one of the fastest-growing retirement communities in the country &mdash; with Williamson County&rsquo;s broad plan menu and three systems to choose among.",
         ["Williamson County offers a wide Advantage menu, every Medigap carrier in Texas and the full Part D lineup. St. David&rsquo;s Georgetown, Baylor Scott &amp; White Round Rock and Ascension Seton Williamson each contract with different carriers, and Austin&rsquo;s specialists are twenty minutes down I-35.",
          "Sun City residents travel more than most and many keep a second home; our Winter Texans guide covers which plans travel. We compare what is sold at your ZIP code with your doctors and calendar in hand."],
         ["St. David&rsquo;s Georgetown Medical Center", "Baylor Scott &amp; White Medical Center&ndash;Round Rock", "Ascension Seton Williamson", "Austin-area specialists"],
         "Georgetown, Sun City Texas, Round Rock, Leander, Liberty Hill, Jarrell, Hutto, Taylor",
         [("Which Medicare plans are available in Georgetown and Sun City?", "Williamson County typically offers a wide Medicare Advantage menu, every Medigap carrier in Texas, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is St. David&rsquo;s Georgetown in my plan&rsquo;s network?", "It depends on the plan and the year. We confirm your hospital and doctors are in-network before you enroll, or steer you to a Medigap policy if you want no network at all."),
          ("How much does your help cost?", COST)],
         ["austin", "fort-cavazos", "waco"]),
    city("midland", "Midland", "Midland County", "west-texas-panhandle", "desert",
         "Midland and Odessa share the Permian Basin&rsquo;s two hospitals and a plan menu that shrank in the surrounding counties for 2026.",
         ["Midland and Ector counties offer a moderate Advantage menu, every Medigap carrier in Texas and the full Part D lineup. Midland Memorial and Medical Center Health System in Odessa contract with different carriers, and Lubbock or Dallas specialists are a long drive away, which is where a Medigap policy&rsquo;s any-provider access matters.",
          "The counties around the Basin were among those that lost Advantage plans for 2026."],
         ["Midland Memorial Hospital", "Medical Center Health System (Odessa)", "Odessa Regional Medical Center", "Big Spring VA Medical Center"],
         "Midland, Odessa, Big Spring, Andrews, Monahans, Fort Stockton, Pecos",
         [("Which Medicare plans are available in Midland and Odessa?", "Midland and Ector counties typically offer a moderate Medicare Advantage menu, every Medigap carrier in Texas, and the full Part D lineup. Surrounding Permian counties have fewer Advantage plans and some lost plans for 2026."),
          ("My plan pulled out of my county in the Basin. What now?", EXIT),
          ("How much does your help cost?", COST)],
         ["lubbock", "el-paso", "amarillo"]),
    city("beaumont", "Beaumont", "Jefferson County", "houston-gulf-coast", "gulf",
         "Beaumont, Port Arthur and Orange &mdash; the Golden Triangle &mdash; have two hospital systems, a moderate plan menu, and Houston&rsquo;s specialists ninety minutes west.",
         ["Jefferson County offers a moderate Advantage menu, every Medigap carrier in Texas and the full Part D lineup. Baptist Hospitals of Southeast Texas and Christus Southeast Texas St. Elizabeth contract with different carriers, and referrals to Houston are common, which an Advantage network may or may not include.",
          "We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["Baptist Hospitals of Southeast Texas", "Christus Southeast Texas St. Elizabeth", "Christus St. Mary (Port Arthur)", "Beaumont VA Outpatient Clinic"],
         "Beaumont, Port Arthur, Orange, Nederland, Groves, Vidor, Lumberton, Silsbee",
         [("Which Medicare plans are available in Beaumont?", "Jefferson County typically offers a moderate Medicare Advantage menu, every Medigap carrier in Texas, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Can I use Houston specialists with a Beaumont Advantage plan?", "Only if they are in that plan&rsquo;s network, which varies. With Original Medicare and a Medigap policy, any Houston provider that accepts Medicare is covered. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["houston", "the-woodlands"]),
]

BASES = [
    dict(slug="fort-cavazos", name="Fort Cavazos (Killeen)", region="central-texas-hill-country", scene="ranch",
         title="Medicare Near Fort Cavazos &amp; Killeen, TX | ECOS Medicare Solutions",
         desc="Medicare for military retirees and veterans around Fort Cavazos, Killeen, Harker Heights and Temple: TRICARE For Life, the Central Texas VA, Darnall, and which plans fit. From a retired Air Force officer.",
         h1="Medicare near Fort Cavazos, Killeen and Harker Heights",
         sub="One of the largest military communities in the world retires here. TRICARE For Life, the Central Texas VA in Temple, Darnall Army Medical Center &mdash; and a Medicare decision that looks different from a civilian one.",
         h2="Why the Medicare choice is different for a Fort Cavazos family",
         intro=["Bell and Coryell counties hold tens of thousands of military retirees, and most of them reach 65 with TRICARE For Life waiting. TFL requires Medicare Parts A and B and then pays secondary to Medicare, so a Medigap policy is usually unnecessary; its pharmacy is creditable, so a Part D plan usually is too. What is left to decide is whether an MA-only Advantage plan adds dental, vision or hearing worth having &mdash; without duplicating the drug coverage you already have.",
                "Veterans without TRICARE use the Central Texas VA in Temple and the Killeen clinic, and here the Part B timing question is the one that matters: VA care is not creditable for Part B, so delaying Part B because you have the VA triggers a lifelong penalty. Darnall Army Medical Center continues to see retirees on a space-available basis; it is not a substitute for Medicare."],
         systems=["Carl R. Darnall Army Medical Center (TRICARE)", "Central Texas VA Health Care System (Temple)", "Baylor Scott &amp; White (Temple, Killeen)", "AdventHealth Central Texas (Killeen)", "Seton Medical Center Harker Heights"],
         communities="Killeen, Harker Heights, Copperas Cove, Temple, Belton, Nolanville, Salado, Lampasas",
         faqs=[("I retired from the Army with TRICARE For Life. Do I need a Medigap policy or Part D?", "Usually neither. TFL pays secondary to Medicare and its pharmacy is creditable drug coverage. An MA-only Advantage plan can add dental or vision without duplicating your drug benefit; we check whether one is worth it for you."),
               ("I use the Temple VA. Do I still need Part B?", "In most cases, yes. VA medical care is not creditable coverage for Part B, so delaying it can trigger a permanent penalty and leaves you without coverage at a non-VA hospital. Enroll on time."),
               ("Can I keep using Darnall after 65?", "Retirees can be seen at Darnall on a space-available basis under TRICARE rules; Medicare does not pay there. Most Fort Cavazos retirees pair TFL with civilian care at Baylor Scott &amp; White, AdventHealth or Seton.")],
         nearby=["waco", "austin", "georgetown"], cta="Retired from Fort Cavazos? Let&rsquo;s sort out TRICARE, the VA and Medicare together."),
    dict(slug="joint-base-san-antonio", name="Joint Base San Antonio", region="san-antonio-south-texas", scene="alamo",
         title="Medicare Near Joint Base San Antonio, TX | ECOS Medicare Solutions",
         desc="Medicare for military retirees around Lackland, Fort Sam Houston and Randolph: TRICARE For Life, Brooke Army Medical Center, the Audie Murphy VA, and which San Antonio plans fit. From a retired Air Force officer.",
         h1="Medicare near Joint Base San Antonio: Lackland, Fort Sam Houston and Randolph",
         sub="Military City USA has more retirees on TRICARE For Life than almost anywhere. Here is how TFL, Brooke Army Medical Center and the Audie Murphy VA fit with Medicare &mdash; from a retired Air Force officer who trained at Lackland.",
         h2="Why the Medicare choice is different around JBSA",
         intro=["Bexar County&rsquo;s retiree population is enormous: Air Force retirees from Lackland and Randolph, Army medical retirees from Fort Sam Houston, and their spouses. Most reach 65 with TRICARE For Life, which requires Medicare Parts A and B, pays secondary to Medicare and carries creditable pharmacy coverage. For a TFL family, a Medigap policy and a Part D plan are usually redundant; the live question is whether an MA-only Advantage plan&rsquo;s dental, vision and hearing extras are worth having.",
                "Brooke Army Medical Center is the largest military hospital in the country and sees retirees on a space-available basis; Medicare does not pay there. The Audie L. Murphy VA Hospital serves veterans without TFL, and for them the Part B timing rule is the one that matters."],
         systems=["Brooke Army Medical Center (TRICARE)", "Wilford Hall Ambulatory Surgical Center (TRICARE)", "Audie L. Murphy VA Hospital", "Methodist Healthcare", "University Health", "Baptist Health System"],
         communities="Universal City, Converse, Schertz, Cibolo, Live Oak, Selma, Lackland-area Westside, Kirby, Windcrest",
         faqs=[("I retired from the Air Force with TRICARE For Life. Which Medicare plan should I pick?", "For most TFL families, Original Medicare Parts A and B with TFL is complete coverage. An MA-only Advantage plan can add dental, vision and hearing without duplicating your pharmacy benefit; we check whether one is worth it for you."),
               ("Does Medicare pay at Brooke Army Medical Center?", "No. BAMC sees retirees on a space-available basis under TRICARE rules. Most JBSA retirees pair TFL with civilian care at Methodist, University Health or Baptist."),
               ("I use the Audie Murphy VA and do not have TRICARE. Do I need Part B?", "In most cases, yes. VA care is not creditable for Part B; delaying it triggers a permanent penalty and leaves you uncovered at a non-VA hospital.")],
         nearby=["san-antonio", "austin", "corpus-christi"], cta="Retired from JBSA? Let&rsquo;s sort out TRICARE, the VA and Medicare together."),
    dict(slug="fort-bliss", name="Fort Bliss (El Paso)", region="west-texas-panhandle", scene="desert",
         title="Medicare Near Fort Bliss &amp; El Paso, TX | ECOS Medicare Solutions",
         desc="Medicare for military retirees around Fort Bliss and El Paso: TRICARE For Life, William Beaumont Army Medical Center, the El Paso VA, and which plans fit. From a retired Air Force officer.",
         h1="Medicare near Fort Bliss and El Paso",
         sub="Fort Bliss retirees have TRICARE For Life, William Beaumont Army Medical Center, the El Paso VA and a border-city care map that reaches into New Mexico. Here is how it fits with Medicare.",
         h2="Why the Medicare choice is different for a Fort Bliss family",
         intro=["El Paso&rsquo;s military-retiree community reaches 65 with TRICARE For Life, which requires Medicare Parts A and B, pays secondary to Medicare and carries creditable pharmacy coverage. A Medigap policy and a Part D plan are usually redundant for a TFL family; the open question is whether an MA-only Advantage plan&rsquo;s extras are worth it, and whether its network reaches the Las Cruces doctors many El Pasoans use.",
                "William Beaumont Army Medical Center sees retirees on a space-available basis; Medicare does not pay there. The El Paso VA Health Care System serves veterans without TFL, for whom the Part B timing rule is the one that matters."],
         systems=["William Beaumont Army Medical Center (TRICARE)", "El Paso VA Health Care System", "University Medical Center of El Paso", "The Hospitals of Providence", "Las Palmas Del Sol Healthcare"],
         communities="Northeast El Paso, Biggs Field area, Horizon City, Socorro, Chaparral and Anthony (NM), Las Cruces-area retirees",
         faqs=[("I retired from Fort Bliss with TRICARE For Life. Do I need anything besides Medicare A and B?", "Usually not. TFL fills Medicare&rsquo;s gaps and its pharmacy is creditable. An MA-only Advantage plan can add dental or vision; we check whether one is worth it and whether its network reaches your doctors."),
               ("Does Medicare pay at William Beaumont?", "No. WBAMC sees retirees on a space-available basis under TRICARE rules. Most Fort Bliss retirees pair TFL with civilian care in El Paso or Las Cruces."),
               ("I use the El Paso VA. Do I need Part B?", "In most cases, yes. VA care is not creditable for Part B; delaying it triggers a permanent penalty.")],
         nearby=["el-paso", "midland", "lubbock"], cta="Retired from Fort Bliss? Let&rsquo;s sort out TRICARE, the VA and Medicare together."),
]
